apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
  labels:
    app: imageapipubsubcomponent
spec:
  type: pubsub.redis
  version: v1
  initTimeout: 30s
  metadata:
    - name: redisHost
      value: localhost:6380
    - name: redisPassword
      value: "S3cr3tPassw0rd!"